{application,metalkia_web_site,
             [{description,"Web-interface for Metalkia"},
              {vsn,"0.1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{mtws_app,[]}},
              {env,[]},
              {modules,[mtws_app,mtws_sup,nitrogen_app,nitrogen_init,
                        nitrogen_sup,nitrogen_webmachine,static_resource,
                        static_route_handler]}]}.
